name: run main.py

on:
  schedule:
    - cron: '*/10 * * * *' # Runs every 10 minutes

# on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # run main.py
        env:
          TWITTER_CK: ${{ secrets.TWITTER_CK }}
          TWITTER_CS: ${{ secrets.TWITTER_CS }}
          TWITTER_T: ${{ secrets.TWITTER_T }}
          TWITTER_TS: ${{ secrets.TWITTER_TS }}
        run: |
          python scrapeCBs_Tweet.py
          # python scrapeFuturecast_Tweet.py
          python scrapeEvents_Tweet.py
          python scrapeCommits_Tweet.py
          # python scrapeOffers_Tweet.py
        
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 
